//this chunk of code was generated by ai

#ifndef ANSI_TUI_H
#define ANSI_TUI_H

#include <stdio.h>

/* ========================================================================== */
/*   TEXT STYLES & RESET                                                      */
/* ========================================================================== */
#define ANSI_RESET            "\033[0m"
#define ANSI_BOLD             "\033[1m"
#define ANSI_DIM              "\033[2m"
#define ANSI_ITALIC           "\033[3m"
#define ANSI_UNDERLINE        "\033[4m"
#define ANSI_BLINK            "\033[5m"
#define ANSI_REVERSE          "\033[7m"
#define ANSI_HIDDEN           "\033[8m"
#define ANSI_STRIKETHROUGH    "\033[9m"

/* ========================================================================== */
/*   FOREGROUND COLORS                                                        */
/* ========================================================================== */
// Standard
#define ANSI_FG_BLACK         "\033[30m"
#define ANSI_FG_RED           "\033[31m"
#define ANSI_FG_GREEN         "\033[32m"
#define ANSI_FG_YELLOW        "\033[33m"
#define ANSI_FG_BLUE          "\033[34m"
#define ANSI_FG_MAGENTA       "\033[35m"
#define ANSI_FG_CYAN          "\033[36m"
#define ANSI_FG_WHITE         "\033[37m"
#define ANSI_FG_DEFAULT       "\033[39m"

// Bright / Intense
#define ANSI_FG_B_BLACK       "\033[90m"
#define ANSI_FG_B_RED         "\033[91m"
#define ANSI_FG_B_GREEN       "\033[92m"
#define ANSI_FG_B_YELLOW      "\033[93m"
#define ANSI_FG_B_BLUE        "\033[94m"
#define ANSI_FG_B_MAGENTA     "\033[95m"
#define ANSI_FG_B_CYAN        "\033[96m"
#define ANSI_FG_B_WHITE       "\033[97m"

/* ========================================================================== */
/*   BACKGROUND COLORS                                                        */
/* ========================================================================== */
// Standard
#define ANSI_BG_BLACK         "\033[40m"
#define ANSI_BG_RED           "\033[41m"
#define ANSI_BG_GREEN         "\033[42m"
#define ANSI_BG_YELLOW        "\033[43m"
#define ANSI_BG_BLUE          "\033[44m"
#define ANSI_BG_MAGENTA       "\033[45m"
#define ANSI_BG_CYAN          "\033[46m"
#define ANSI_BG_WHITE         "\033[47m"
#define ANSI_BG_DEFAULT       "\033[49m"

// Bright / Intense
#define ANSI_BG_B_BLACK       "\033[100m"
#define ANSI_BG_B_RED         "\033[101m"
#define ANSI_BG_B_GREEN       "\033[102m"
#define ANSI_BG_B_YELLOW      "\033[103m"
#define ANSI_BG_B_BLUE        "\033[104m"
#define ANSI_BG_B_MAGENTA     "\033[105m"
#define ANSI_BG_B_CYAN        "\033[106m"
#define ANSI_BG_B_WHITE       "\033[107m"

/* ========================================================================== */
/*   SCREEN / BUFFER MANIPULATION                                             */
/* ========================================================================== */
#define ANSI_CLR_TO_SCREEN_END  "\033[0J"
#define ANSI_CLR_TO_SCREEN_BEG  "\033[1J"
#define ANSI_CLEAR_SCREEN       "\033[2J"
#define ANSI_CLEAR_ALL          "\033[3J" // Clears screen and scrollback buffer

#define ANSI_CLR_TO_LINE_END    "\033[0K"
#define ANSI_CLR_TO_LINE_BEG    "\033[1K"
#define ANSI_CLEAR_LINE         "\033[2K"

// Alternate Screen Buffer (Crucial for TUIs so you don't mess up the user's terminal history)
#define ANSI_ALT_BUFFER_ON      "\033[?1049h"
#define ANSI_ALT_BUFFER_OFF     "\033[?1049l"

/* ========================================================================== */
/*   CURSOR CONTROL (STATIC STRINGS)                                          */
/* ========================================================================== */
#define ANSI_CURSOR_HOME        "\033[H"
#define ANSI_CURSOR_HIDE        "\033[?25l"
#define ANSI_CURSOR_SHOW        "\033[?25h"
#define ANSI_CURSOR_SAVE        "\033[s"
#define ANSI_CURSOR_RESTORE     "\033[u"

/* ========================================================================== */
/*   DYNAMIC ACTIONS (FUNCTION-LIKE MACROS)                                   */
/* ========================================================================== */
// 1-Based Positioning: (1,1) is the top-left corner
#define tui_goto(row, col)       "\033[%d;%dH", (row), (col)

#define tui_move_up(n)           "\033[%dA", (n)
#define tui_move_down(n)         "\033[%dB", (n)
#define tui_move_right(n)        "\033[% dC", (n)
#define tui_move_left(n)         "\033[%dD", (n)

// 256-Color Support (0 - 255)
#define tui_set_fg_256(color)    "\033[38;5;%dm", (color)
#define tui_set_bg_256(color)    "\033[48;5;%dm", (color)

// True Color / RGB Support (0-255 for r, g, b)
#define tui_set_fg_rgb(r,g,b)    "\033[38;2;%d;%d;%dm", (r), (g), (b)
#define tui_set_bg_rgb(r,g,b)    "\033[48;2;%d;%d;%dm", (r), (g), (b)

/* ========================================================================== */
/*   MOUSE TRACKING (OPTIONAL FOR ADVANCED TUIS)                              */
/* ========================================================================== */
#define ANSI_MOUSE_ENABLE       "\033[?1000h\033[?1006h" // Enable mouse clicks & SGR extended mode
#define ANSI_MOUSE_DISABLE      "\033[?1000l\033[?1006l"

#endif // ANSI_TUI_H